syntax = "proto3";
package splitsecure.attestation.v1;

// AndroidKeyAttestationResult contains the result of verifying an Android Key Attestation.
message AndroidKeyAttestationResult {
  bytes key_id = 1;
  bytes attestation_challenge = 2;
  SecurityLevel attestation_security_level = 3;
  SecurityLevel key_mint_security_level = 4;
  RootOfTrust root_of_trust = 5;
  DeviceIdentity device_identity = 6;
  ApplicationIdentity application_identity = 7;

  enum SecurityLevel {
    SECURITY_LEVEL_UNSPECIFIED = 0;
    SECURITY_LEVEL_SOFTWARE = 1;
    SECURITY_LEVEL_TRUSTED_ENVIRONMENT = 2;
    SECURITY_LEVEL_STRONG_BOX = 3;
  }

  message RootOfTrust {
    bytes verified_boot_key = 1;
    bool device_locked = 2;
    VerifiedBootState verified_boot_state = 3;
    bytes verified_boot_hash = 4;
  }

  enum VerifiedBootState {
    VERIFIED_BOOT_STATE_UNSPECIFIED = 0;
    VERIFIED_BOOT_STATE_VERIFIED = 1;
    VERIFIED_BOOT_STATE_SELF_SIGNED = 2;
    VERIFIED_BOOT_STATE_UNVERIFIED = 3;
    VERIFIED_BOOT_STATE_FAILED = 4;
  }

  message DeviceIdentity {
    string brand = 1;
    string device = 2;
    string product = 3;
    string serial_number = 4;
    string manufacturer = 5;
    string model = 6;
    repeated string imeis = 7;
    string meid = 8;
  }

  message ApplicationIdentity {
    repeated PackageInfo packages = 1;
    repeated bytes signature_digests = 2;

    message PackageInfo {
      string name = 1;
      int64 version = 2;
    }
  }
}
