syntax = "proto3";
package splitsecure.attestation.v1;

import "google/protobuf/timestamp.proto";
import "splitsecure/attestation/v1/android_key_attestation_result.proto";
import "splitsecure/attestation/v1/apple_device_check_attestation_result.proto";
import "splitsecure/attestation/v1/aws_nitro_attestation_result.proto";

// Result is the result of verifying an attestation.
message Result {
  google.protobuf.Timestamp not_before = 1;
  google.protobuf.Timestamp not_after = 2;
  PlatformInfo platform = 3;

  // PlatformInfo contains platform-specific attestation verification results.
  message PlatformInfo {
    oneof union {
      AppleDeviceCheckAttestationResult apple_dc = 1;
      AWSNitroAttestationResult aws_nitro = 2;
      AndroidKeyAttestationResult android_key = 3;
    }
  }
}
