syntax = "proto3";
package splitsecure.requestsigning.v1;

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
import "splitsecure/delegationgraph/v1/graph.proto";
import "splitsecure/hybridkeyset/v1/signature.proto";

message SignedRequest {
  // requestor_id refers to the requestor which is granted the ability to perform the action.
  bytes requestor_id = 2;

  splitsecure.delegationgraph.v1.Graph graph = 3;
  splitsecure.hybridkeyset.v1.Signature signature = 4;

  // contains SignedRequest_Authenticated
  bytes authenticated = 1;
  message Authenticated {
    google.protobuf.Any base_request = 1;
    google.protobuf.Timestamp created_on = 2;
  }
}
