syntax = "proto3";
package splitsecure.saml2.v2;

import "splitsecure/saml2/v2/metadata.proto";
import "splitsecure/saml2/v2/providers/v1/known_provider.proto";
import "splitsecure/teamresource/v1/base_resource_attributes.proto";

message SAML2ServiceProvider {
  reserved 1, 2, 6, 7, 8, 9;
  reserved 100 to 116;

  // idp_serial is meant to match the serial in the authenticated IdPState.
  uint64 idp_serial = 3;

  // idp_coord_id_hint is the coordination-layer ID of the IdP resource,
  // used as a hint by the coordination service to look up the matching
  // IdP for this SP.
  string idp_coord_id_hint = 4;

  splitsecure.saml2.v2.Metadata metadata = 5;

  splitsecure.teamresource.v1.BaseResourceAttributes base_resource_attributes = 10;

  splitsecure.saml2.v2.providers.v1.KnownProvider known_provider = 200;
}
